<?php
$proc_sessions="/proc/net/iet/session";
$ietd_config_file='/etc/iet/ietd.conf';
$ietd_init_allow="/etc/iet/initiators.allow";
$ietd_target_allow="/etc/iet/targets.allow";
$ietadm="/usr/sbin/ietadm";
$sudo="/usr/bin/sudo";
$proc_volumes="/proc/net/iet/volume";
$cat="/bin/cat";
$service="/usr/sbin/service";
$lvs="/sbin/lvs";
$vgs="/sbin/vgs";
$pvs="/sbin/pvs";
$lvcreate="/sbin/lvcreate";
$lvextend="/sbin/lvextend";
$lvremove="/sbin/lvremove";
$lsblk="/bin/lsblk";
$service_name="iscsitarget";
$iqn="iqn.2014-12.com.example.iscsi";
?>